### ISSUE TITLE
Non-existing function used in README

### ISSUE THREAD

**Issue by Lyannic** [bcgsc/ntHash#10]
You are referencing a non-existing function (NT64) in the README.
```cpp    
string kmer = seq.substr(0, k);
uint64_t hVal=0;
hVal = NT64(kmer.c_str(), k); // initial hash value
...
for (size_t i = 0; i < seq.length() - k; i++) 
{
      hVal = NT64(hVal, seq[i], seq[i+k], k); // consecutive hash values
      ...
}
```

I only find canonical or multi-hash functions in the current source code. Which function is meant to be used, if you don't want to hash canonical or multi-hash? Just the multi-hash function with m=1? 
If this function really isn't present, could you please remove it from the README, to prevent further confusion?

**Comment by mohamadi** [comment]
Hi @Lyannic, Thanks for catching this. It should be NTF64 instead. I just fixed it.
