### ISSUE TITLE
Unarchive the repository to let community easily contribute to ntHash

### ISSUE THREAD

**Issue by mohamadi** [bcgsc/ntHash#19]
Hi @vlad0x00, lets unarchive ntHash repo to avoid confusion. People in the community will be contributing to this repo.

**Comment by mohamadi** [comment]
it's a good idea to automatically sync between btllib and nthash rather than have the development be done there.

**Comment by vlad0x00** [comment]
Automatic syncing might not be trivial, though, since btllib nthash code has been changed to fit the style guidelines and has been made less verbove/slighty modified. I could perhaps sync this repo with the btllib version, if you think that's a good idea.

**Comment by mohamadi** [comment]
it's better to have ntHash as the main upstream repo and sync btllib or any other repo with it.

**Comment by vlad0x00** [comment]
ntHash repo has a lot of extra files that would bloat btllib. One thing we could do, though, that's a bit extra work, is to unarchive this repo and simply copy any functionality users contribute here to btllib.
