### ISSUE TITLE
Calls to omp timing functions when _OPENMP is not defined

### ISSUE THREAD

**Issue by rsharris** [bcgsc/ntHash#2]
In nttest,cpp, in the function nthashBF(), omp_get_wtime() is called even if _OPENMP is not defined.

If not having OpenMP is a supported configuration, it seems like these four calls should be redirected to some other function (get_time?) if _OPENMP is not defined.

**Comment by rsharris** [comment]
Similarly, an attempt to set up the build with ./configure --disable-openmp , suggested by ./configure --help, fails with the message "configure: error: NTHASH must be compiled with a C++ compiler that supports OpenMP threading".

**Comment by mohamadi** [comment]
@rsharris Thanks Bob for reporting these issues. I'll fix them shortly.

**Comment by mohamadi** [comment]
@rsharris just fixed the openmp issue.
