### ISSUE TITLE
Create a native Python interface for ntHash

### ISSUE THREAD

**Issue by sjackman** [bcgsc/ntHash#8]
See https://docs.python.org/3/extending/extending.html

**Comment by luizirber** [comment]
I can help with this if you want some feedback

**Comment by sjackman** [comment]
Sure, thanks!
Hamid @mohamadi is working on this feature as we speak. Any suggestions for the Python API?

**Comment by mohamadi** [comment]
@luizirber is there a standard way for wrapping ntHash in a Python API?

**Comment by mohamadi** [comment]
@luizirber thanks, I'll start with the Cython wrapper.

**Comment by parham-k** [comment]
Closing, we have Python wrappers in ntHash2 (implemented with SWIG in [btllib](https://github.com/bcgsc/btllib)).

**Comment by rchikhi** [comment]
Anecdotally, a pure Python ntHash1 implementation is here: https://gist.github.com/rchikhi/ef2a6371c1a6dc2ab53c572ff6890cea
